name: A4

on:
  workflow_dispatch:

jobs:
  build-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and activate virtual environment 
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install cowsay
          pip freeze > requirements.txt

      - name: Package environment 
        run: tar -czf environment.tar.gz .venv
     
      - name: Upload environment artifact 
        uses: actions/upload-artifact@v4
        with:
          name: python-environment
          path: |
            environment.tar.gz
            requirements.txt
          retention-days: 1

  use-environment: 
    runs-on: ubuntu-latest
    needs: build-environment 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download environment artifact
        uses: actions/download-artifact@v4
        with:
          name: python-environment
          path: .

      - name: Extract environment
        run: tar -xzf environment.tar.gz

      - name: Verify environment
        run: |
          source .venv/bin/activate
          python -c "import cowsay; print('Cowsay module found!')"

      - name: Run Python script
        run: |
          source .venv/bin/activate
          python .github/scripts/script.py

  confirmation:
    runs-on: ubuntu-latest
    needs: use-environment
    steps:
      - name: Confirmation
        run: echo "Cowsay said!"