name: A4

on:
  workflow_dispatch:

jobs:
  build-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Activate virtual environment and install dependencies
        run: |
          source .venv/bin/activate  # Ativa o ambiente virtual
          pip install cowsay        # Instala cowsay DENTRO do ambiente virtual
          # Opcional: Para registrar as dependências instaladas
          # pip freeze > requirements.txt

      # REMOVIDO: O passo "Install dependencies" redundante foi removido.
      # A instalação já foi feita no passo anterior, dentro do venv.

      - name: Package environment
        # CORREÇÃO: Adicionado o caminho para o diretório .venv a ser empacotado
        # Incluímos também o requirements.txt se ele tivesse sido gerado.
        run: tar -czf environment.tar.gz .venv # Se tivesse gerado o requirements.txt: .venv requirements.txt

      - name: Upload environment artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-environment
          path: environment.tar.gz
          retention-days: 1

  use-environment:
    runs-on: ubuntu-latest
    needs: build-environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download environment artifact
        uses: actions/download-artifact@v4
        with:
          name: python-environment
          path: .

      - name: Extract environment
        run: tar -xzf environment.tar.gz

      - name: Run Python script
        # CORREÇÃO: Ativar o ambiente virtual ANTES de rodar o script python.
        # Isso garante que o Python do ambiente virtual, com 'cowsay' instalado, seja usado.
        run: |
          source .venv/bin/activate
          python .github/scripts/script.py

  confirmation:
    runs-on: ubuntu-latest
    needs: use-environment
    steps:
      - name: Confirmation
        run: echo "Cowsay said!"