name: Run a Python Script

on:
  push:
    branches:
      - main #
  workflow_dispatch:

jobs:
  prepares-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cowsay

  execute-script:
    runs-on: ubuntu-latest
    needs: prepares-env

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Python script
        run: python .github/scripts/script.py

  confirmation:
    runs-on: ubuntu-latest
    needs: execute-script
    steps:
      - name: Confirmation
        run: echo "Cowsay said!"
