name: Run a shell script

on:
  workflow_dispatch:
    inputs:
        NameVariable: #input do workflow
          description: "Enter your name"
          required: true
          type: string

jobs:
  first-job:
    runs-on: ubuntu-latest
    outputs:
        output1: $ {{steps.set_output.outputs.name_variable}} #output de saida do job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: First job shell command
        id: set_output
        run: echo "name_variable=Hello, ${{ github.event.inputs.NameVariable }}" >> $GITHUB_OUTPUT
        #output de saida do step

  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    if: ${{ always() }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Second job shell command
        run: echo "Hello, second"

      - name: Receive output
        run: echo "${{ needs.first-job.outputs.output1 }}" #recebe a saida do job 1

  third-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Shell command
        run: echo "Hello, third"